### PR TITLE
Goa 2646 new slim header

### PR DESCRIPTION
**Pull request by markbingley**

### CODE REVIEW

**Comment by markbingley** [comment]
Code added to correct the width of the search bar on the home page

**Comment by markbingley** [comment]
I decided not to do medium-12, as that moves the buttons directly below the logo, and to me it looks a little bit busy/ugly.
I felt the offset was more visually pleasing....

**Comment by xwatkins** [comment]
Just spoke to Ken, they have actually been working on a compact header,
prototype stage at the moment but there should be a release candidate next
week
https://ebiwd.github.io/EBI-Pattern-library/meta-patterns/masthead-compact/#component-detail

**Comment by markbingley** [comment]
I thought the point of putting the header in now was to meet the need for the Demo.   We can always rework it later to use the new “ken” standard.  

I was under the impression that the demo this week was the driver for including this now.

**Pull request closed without merging**
