### PR TITLE
Goa 3235 and or button

### PR DESCRIPTION
**Pull request by ljgarcia**

### CODE REVIEW

**Comment by xwatkins** [comment]
Could the AND/OR be a select menu rather than an autocomplete?

**Comment by ljgarcia** [comment]
Select rather than autocomplete could be useful for other boxes there as well, and more improvements could be introduced as well. Do you want to change this one to select now as part of this Pr? or do you want to collect all improvements and create a new issue for it?

**Comment by xwatkins** [comment]
No, the others have to be autocomplete as there are too long a list for a select (see with Tony if required)

**Comment by ljgarcia** [comment]
Done, and/or is a select now. Please have a look. I will talk to @tonysawfordebi regarding any other improvements.

**Pull request merged**
